### ISSUE TITLE
Stukkend

### ISSUE THREAD

**Issue by wpswart006** [phzietsman/terraform-provider-awsx#7]
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 82 [running]:
github.com/phzietsman/terraform-provider-awsx/internal/provider.resourceControlTowerAccountVendingCreate(0xc0002fc850, 0x417c9e0, 0xc000350000, 0x2, 0x80e1420)
        /Users/paulzietsman/go/src/github.com/phzietsman/terraform-provider-awsx/internal/provider/resource_controltower_vend_account.go:86 
+0x1048
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000160b80, 0xc0003d43c0, 0xc00021aa40, 0x417c9e0, 0xc000350000, 0x4002801, 0xc000124b18, 0xc00023fe90)
        /Users/paulzietsman/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.1/helper/schema/resource.go:305 +0x36c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000160c00, 0xc0000e58e0, 0xc0003d43c0, 0xc00021aa40, 0xc0001d8aa8, 0xc00020a038, 0x4004880)
        /Users/paulzietsman/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.1/helper/schema/provider.go:294 +0xa0
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000006aa0, 0x54eed60, 0xc00023e300, 0xc000206e40, 0xc000006aa0, 0xc00023e300, 0xc00019ba48)
        /Users/paulzietsman/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.1/internal/helper/plugin/grpc_provider.go:885 +0x889  
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x4ae5280, 0xc000006aa0, 0x54eed60, 0xc00023e300, 0xc000206de0, 0x0, 0x54eed60, 0xc00023e300, 0xc0002a2000, 0xcd6)
        /Users/paulzietsman/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.4.1/internal/tfplugin5/tfplugin5.pb.go:3189 +0x21e      
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013c2c0, 0x5507ba0, 0xc000084d80, 0xc0004e8400, 0xc00016e1b0, 0x80a4740, 0x0, 0x0, 0x0)
        /Users/paulzietsman/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x467
google.golang.org/grpc.(*Server).handleStream(0xc00013c2c0, 0x5507ba0, 0xc000084d80, 0xc0004e8400, 0x0)
        /Users/paulzietsman/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xd44
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00008e140, 0xc00013c2c0, 0x5507ba0, 0xc000084d80, 0xc0004e8400)
        /Users/paulzietsman/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xa8
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/paulzietsman/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa8

**Comment by willem-swart-absa** [comment]
Can confirm. "Stukkend"
